[build-system]
requires = ["hatchling>=1.25", "hatch-vcs>=0.4", "setuptools-scm>=8"]
build-backend = "hatchling.build"

[project]
name = "sortune-adapters"
description = "External integrations for Sortune (YouTube Music, storage, telemetry)"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "pydantic>=2.11.7",
    "redis>=5.0",
]

[tool.hatch.build.targets.wheel]
packages = ["sortune_adapters"]

[tool.hatch.version]
# This is the correct way to specify the version file
source = "vcs"
path = "sortune_adapters/_version.py"

[tool.hatch.version.vcs]
# These options are passed to setuptools-scm
# Assumes this file is two directories deep from the repo root (e.g., repo-root/packages/adapters/pyproject.toml)
root = "../../"
search_parent_directories = true
tag_regex = "^v(?P<version>\\d+\\.\\d+\\.\\d+.*)$"
fallback_version = "0.0.0"