[build-system]
requires = ["hatchling>=1.25", "hatch-vcs>=0.4"]
build-backend = "hatchling.build"

[project]
name = "sortune-ai"
description = "Prompts, schemas, and LLM utilities for Sortune"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    "pydantic>=2.11.7",
]

[tool.hatch.build.targets.wheel]
packages = ["sortune_ai"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "sortune_ai/_version.py"
