[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sortune-core"
version = "0.0.0"
description = "Core domain models, services, and rules for Sortune"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.11.7"]

[tool.hatch.build.targets.wheel]
packages = ["sortune_core"]
