name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: ["v*.*.*"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: uv venv

    - name: Get latest tag and set version
      id: meta
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "tag_name=$TAG" >> $GITHUB_OUTPUT
        echo "version=${TAG#v}" >> $GITHUB_OUTPUT

    - name: Set version env var for setuptools-scm
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        uv pip compile pyproject.toml --extra dev | uv pip install -r -
        uv pip install -e packages/core -e packages/adapters -e packages/ai -e apps/api -e apps/worker
        uv pip install streamlit

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

    - name: Test
      run: make test
