name: Update CHANGELOG.md via PR (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to add to CHANGELOG (e.g., v0.1.0)"
        required: true

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: changelog-${{ github.event.inputs.tag }}
  cancel-in-progress: false

jobs:
  changelog_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Verify tag exists and is on main
        run: |
          set -euo pipefail
          TAG="${{ github.event.inputs.tag }}"
          # Ensure the tag exists
          git fetch --tags --force
          if ! git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "❌ Tag $TAG not found"; exit 1
          fi
          # Ensure the tag commit is reachable from main
          SHA="$(git rev-list -n1 "$TAG")"
          git fetch origin main --prune --depth=0
          if git merge-base --is-ancestor "$SHA" "origin/main"; then
            echo "✅ $TAG is on main"
          else
            echo "❌ $TAG is not on main"; exit 1
          fi

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Prepend new section to CHANGELOG.md
        run: |
          set -euo pipefail
          TAG="${{ github.event.inputs.tag }}"
          test -f CHANGELOG.md || echo "# Changelog" > CHANGELOG.md
          # Render the section for exactly this tag using your cliff.toml
          git-cliff --config cliff.toml --tag "$TAG" > NEW.md
          # Prepend with a blank line separator between sections
          awk 'FNR==1 && NR!=1{print ""}1' NEW.md CHANGELOG.md > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          rm NEW.md
          git add CHANGELOG.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-changelog-${{ github.event.inputs.tag }}
          title: "chore(changelog): add ${{ github.event.inputs.tag }}"
          commit-message: "chore(changelog): add ${{ github.event.inputs.tag }}"
          body: "Automated changelog update for ${{ github.event.inputs.tag }}."
          base: main
