name: Update CHANGELOG.md via PR (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to add to CHANGELOG (e.g., v0.1.0)"
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  changelog_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Install git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          version: "latest"

      - name: Prepend new section to CHANGELOG.md
        run: |
          test -f CHANGELOG.md || echo "# Changelog" > CHANGELOG.md
          git-cliff --config cliff.toml --tag "${{ github.event.inputs.tag }}" > NEW.md
          awk 'FNR==1 && NR!=1{print ""}1' NEW.md CHANGELOG.md > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          rm NEW.md
          git add CHANGELOG.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/update-changelog-${{ github.event.inputs.tag }}
          title: "chore(changelog): add ${{ github.event.inputs.tag }}"
          commit-message: "chore(changelog): add ${{ github.event.inputs.tag }}"
          body: "Automated changelog update for ${{ github.event.inputs.tag }}."
          base: main
