name: Draft release notes
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
